# Generated by Django 5.2.13 on 2026-04-21 00:16

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PROVENTO', 'Provento (+)'), ('DESCONTO', 'Desconto (-)')], max_length=10)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(help_text='Ex: Júnior, Pleno, Sênior', max_length=50)),
                ('carga_horaria', models.IntegerField(default=44)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(editable=False, max_length=20, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[core.models.validar_cpf])),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('data_admissao', models.DateField()),
                ('dependentes', models.IntegerField(default=0)),
                ('nome_mae', models.CharField(max_length=150)),
                ('nome_pai', models.CharField(blank=True, max_length=150)),
                ('endereco_completo', models.TextField()),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('tipo', models.CharField(choices=[('MENSAL', 'Mensal'), ('FERIAS', 'Férias'), ('DECIMO', '13º Salário'), ('RESCISAO', 'Rescisão')], default='MENSAL', max_length=10)),
                ('salario_base_Snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fgts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_proventos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fechada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
            options={
                'unique_together': {('funcionario', 'mes', 'ano', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Falta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('justificada', models.BooleanField(default=False)),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificativas/')),
                ('observacao', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.folhapagamento')),
            ],
        ),
    ]
