# Generated by Django 5.2.13 on 2026-04-19 15:57

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PROVENTO', 'Provento'), ('DESCONTO', 'Desconto')], max_length=10)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('carga_horaria', models.IntegerField(default=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[core.models.validar_cpf])),
                ('data_nascimento', models.DateField(blank=True, null=True, validators=[core.models.validar_idade])),
                ('dependentes', models.IntegerField(default=0)),
                ('escolaridade', models.CharField(choices=[('FUNDAMENTAL', 'Fundamental'), ('MEDIO', 'Médio'), ('SUPERIOR', 'Superior'), ('POS', 'Pós-graduação')], default='MEDIO', max_length=50)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASADO', 'Casado'), ('DIVORCIADO', 'Divorciado')], default='SOLTEIRO', max_length=20)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_admissao', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MENSAL', 'Mensal'), ('FERIAS', 'Férias'), ('DECIMO', '13º')], max_length=10)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salario_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_proventos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('irrf', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fgts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fechada', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ItemFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folhapagamento')),
            ],
        ),
    ]
