# Generated by Django 5.2.13 on 2026-04-21 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdepartamentos', to='core.departamento'),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='data_rescisao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='dias_gozo_ferias',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='parcela_13o',
            field=models.IntegerField(blank=True, choices=[(1, '1ª Parcela'), (2, '2ª Parcela'), (0, 'Parcela Única')], null=True),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='salario_base_Snapshot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
