# Generated by Django 5.2.13 on 2026-04-21 16:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departamento_parent_folhapagamento_data_rescisao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
