# Generated by Django 5.2.13 on 2026-04-21 21:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cargo_salario_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='salario_base',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario_base',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
