# Generated by Django 5.2.13 on 2026-04-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_funcionario_salario_bruto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='salario_bruto',
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
