# Generated by Django 5.2.13 on 2026-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_funcionario_salario_bruto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='saldo_salario_rescisao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='terco_constitucional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='valor_ferias_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
