# Generated by Django 5.2.13 on 2026-04-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_folhapagamento_saldo_salario_rescisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aplica_13',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='incide_fgts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='incide_inss',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='incide_irrf',
            field=models.BooleanField(default=True),
        ),
    ]
