# Generated by Django 5.2.13 on 2026-04-23 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_evento_aplica_13_evento_incide_fgts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='motivo_rescisao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
