# Generated by Django 5.2.13 on 2026-04-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_falta_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falta',
            name='sexo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True),
        ),
    ]
