# Generated by Django 5.2.13 on 2026-04-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_falta_sexo_funcionario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo_acesso',
            field=models.CharField(choices=[('MASTER', 'Administrador de RH'), ('USUARIO', 'Visualização')], default='USUARIO', max_length=10),
        ),
    ]
