# Generated by Django 5.2.13 on 2026-04-28 23:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_funcionario_tipo_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_acesso',
            field=models.CharField(choices=[('MASTER', 'Master (Acesso Total)'), ('USUARIO', 'Usuário (Apenas Visualização)')], default='USUARIO', max_length=10, verbose_name='Nível de Acesso'),
        ),
    ]
