# Generated by Django 5.2.13 on 2026-05-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_funcionario_ativo_alter_funcionario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='percentual',
        ),
    ]
