# Generated by Django 5.2.13 on 2026-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_folhapagamento_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falta',
            old_name='documento',
            new_name='atestado',
        ),
        migrations.RenameField(
            model_name='falta',
            old_name='observacao',
            new_name='motivo',
        ),
        migrations.AddField(
            model_name='falta',
            name='ano_referencia',
            field=models.IntegerField(default=0, verbose_name='Ano da Folha (Ex: 2026)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='falta',
            name='mes_referencia',
            field=models.IntegerField(default=0, verbose_name='Mês da Folha (Ex: 4)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='falta',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='falta',
            name='data',
            field=models.DateField(verbose_name='Data da Falta'),
        ),
    ]
