# Generated by Django 5.2.13 on 2026-05-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_documento_falta_atestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhapagamento',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
