# Generated by Django 5.2.13 on 2026-04-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='folhapagamento',
            name='unique_folha_por_tipo',
        ),
        migrations.RenameField(
            model_name='folhapagamento',
            old_name='salario_bruto',
            new_name='salario_base',
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='adicionais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='horas_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='salario_liquido',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
