# Generated by Django 5.2.13 on 2026-04-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_folhapagamento_unique_folha_por_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PROVENTO', 'Provento'), ('DESCONTO', 'Desconto')], max_length=10)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='folhapagamento',
            unique_together={('funcionario', 'mes', 'ano')},
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='fgts',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='total_descontos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='total_proventos',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.CreateModel(
            name='ItemFolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evento')),
                ('folha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.folhapagamento')),
            ],
        ),
        migrations.RemoveField(
            model_name='folhapagamento',
            name='adicionais',
        ),
        migrations.RemoveField(
            model_name='folhapagamento',
            name='descontos',
        ),
        migrations.RemoveField(
            model_name='folhapagamento',
            name='faltas',
        ),
        migrations.RemoveField(
            model_name='folhapagamento',
            name='horas_extras',
        ),
    ]
