# Generated by Django 5.2.13 on 2026-04-12 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_alter_folhapagamento_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folhapagamento',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='folhapagamento',
            name='inss',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemfolha',
            name='folha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.folhapagamento'),
        ),
        migrations.AlterField(
            model_name='itemfolha',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
