# Generated by Django 5.2.13 on 2026-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_folhapagamento_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='salario_base',
        ),
        migrations.RemoveField(
            model_name='folhapagamento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='fgts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='inss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='salario_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='salario_liquido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='total_descontos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='folhapagamento',
            name='total_proventos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='itemfolha',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
