# Generated by Django 5.2.13 on 2026-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_cargo_salario_base_remove_folhapagamento_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='irrf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
