# Generated by Django 5.2.13 on 2026-04-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_folhapagamento_irrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='tipo',
            field=models.CharField(choices=[('MENSAL', 'Mensal'), ('FERIAS', 'Férias'), ('DECIMO', '13º')], default='MENSAL', max_length=10),
        ),
    ]
