# Generated by Django 5.2.13 on 2026-04-14 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_folhapagamento_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolhaDecimoTerceiro',
            fields=[
            ],
            options={
                'verbose_name': 'Folha de 13º',
                'verbose_name_plural': 'Folhas de 13º',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.folhapagamento',),
        ),
        migrations.CreateModel(
            name='FolhaFerias',
            fields=[
            ],
            options={
                'verbose_name': 'Folha de Férias',
                'verbose_name_plural': 'Folhas de Férias',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.folhapagamento',),
        ),
        migrations.CreateModel(
            name='FolhaMensal',
            fields=[
            ],
            options={
                'verbose_name': 'Folha Mensal',
                'verbose_name_plural': 'Folhas Mensais',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.folhapagamento',),
        ),
    ]
