"""
Django settings for rhsmart project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path

# Caminho base do projeto
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SEGURANÇA ---
# No Railway, você criará uma variável chamada SECRET_KEY. 
# Se não houver, ele usa essa de fallback para testes locais.
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-df8w0zb!%3olt+6bl0l7%k^gkfk5-n*)(rlb!&t85&p=4c97=h')

# No Railway, coloque a variável DEBUG como False.
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# '*' permite acesso de qualquer domínio gerado pelo Railway
ALLOWED_HOSTS = ['*', '127.0.0.1', 'localhost']

# --- DEFINIÇÃO DE APLICATIVOS ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core', # Seu app principal
]

# --- MIDDLEWARE (WhiteNoise adicionado para arquivos estáticos) ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Essencial para o deploy
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rhsmart.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rhsmart.wsgi.application'

# 1. Tenta pegar o link do Railway (ele pode usar qualquer um desses dois nomes)
# Se não encontrar nenhum, db_url ficará como None
# 1. Busca a URL nas variáveis do Railway
db_url = os.getenv('DATABASE_URL', os.getenv('RAILWAY_DATABASE_URL'))

# 2. Configura o banco (SEM fallback para localhost)
DATABASES = {
    'default': dj_database_url.config(
        default=db_url,
        conn_max_age=600
    )
}
# --- VALIDAÇÃO DE SENHAS ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- INTERNACIONALIZAÇÃO ---
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# --- ARQUIVOS ESTÁTICOS (CSS, JS, IMAGES) ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Armazenamento com compressão para o Railway
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- ARQUIVOS DE MÍDIA (Atestados, etc) ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CONFIGURAÇÕES DE LOGIN ---
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

# --- E-MAIL (Console para testes) ---
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Chave padrão para IDs
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'